import './globals.css';
import { Rubik } from 'next/font/google';

// components
import NavBar from './components/NavBar';

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Help Desk',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
